import type { Severity } from './enums.js';

/** Événements du mouchard / journal d'audit (§6.16). */
const events = {
  SALE_CANCELLED: { severity: 'CRITICAL', label: 'Vente annulée' },
  SALE_MODIFIED: { severity: 'CRITICAL', label: 'Vente modifiée' },
  SALE_VALIDATED: { severity: 'INFO', label: 'Vente validée' },
  CART_LINE_REMOVED: { severity: 'WARNING', label: 'Ligne retirée du panier' },
  DRAFT_SALE_DISCARDED: { severity: 'WARNING', label: 'Panier / vente en attente abandonné' },
  DISCOUNT_OVER_LIMIT: { severity: 'WARNING', label: 'Remise au-delà du plafond' },
  PRICE_OVERRIDE: { severity: 'WARNING', label: 'Prix modifié en vente' },
  SALE_BELOW_COST: { severity: 'WARNING', label: 'Vente sous le coût du lot' },
  LOT_FORCED: { severity: 'WARNING', label: 'Lot forcé hors règle FEFO/FIFO' },
  DOCUMENT_REPRINTED: { severity: 'INFO', label: 'Document réimprimé' },
  CASH_DRAWER_OPENED: { severity: 'WARNING', label: 'Tiroir-caisse ouvert sans vente' },
  CASH_SESSION_OPENED: { severity: 'INFO', label: 'Caisse ouverte' },
  CASH_SESSION_CLOSED: { severity: 'INFO', label: 'Caisse clôturée' },
  CASH_MOVEMENT: { severity: 'WARNING', label: 'Mouvement de caisse manuel' },
  CUSTOMER_RETURN: { severity: 'WARNING', label: 'Retour client' },
  CASH_REFUND: { severity: 'WARNING', label: 'Remboursement en espèces' },
  PAYMENT_RECEIVED: { severity: 'INFO', label: 'Règlement enregistré' },
  PAYMENT_ALLOCATED: { severity: 'INFO', label: 'Lettrage' },
  PAYMENT_CANCELLED: { severity: 'CRITICAL', label: 'Règlement annulé' },
  CHEQUE_BOUNCED: { severity: 'CRITICAL', label: 'Chèque impayé' },
  CHEQUE_STATUS_CHANGED: { severity: 'INFO', label: 'Statut de chèque modifié' },
  STOCK_ADJUSTMENT: { severity: 'WARNING', label: 'Ajustement de stock' },
  ADJUSTMENT_DECLARED: { severity: 'INFO', label: 'Ajustement déclaré (à valider)' },
  ADJUSTMENT_REJECTED: { severity: 'INFO', label: 'Ajustement rejeté' },
  INVENTORY_STARTED: { severity: 'INFO', label: 'Inventaire ouvert' },
  INVENTORY_VALIDATED: { severity: 'WARNING', label: 'Inventaire validé' },
  INVENTORY_CANCELLED: { severity: 'WARNING', label: 'Inventaire annulé' },
  DESTRUCTION: { severity: 'WARNING', label: 'Destruction de périmés' },
  RECEIPT_VALIDATED: { severity: 'INFO', label: 'Réception validée' },
  RECEIPT_DRAFT_DISCARDED: { severity: 'INFO', label: 'Brouillon de réception abandonné' },
  RECEIPT_CANCELLED: { severity: 'CRITICAL', label: 'Réception annulée' },
  SUPPLIER_RETURN: { severity: 'WARNING', label: 'Retour fournisseur' },
  SUPPLIER_CREDIT_RECEIVED: { severity: 'INFO', label: 'Avoir fournisseur reçu' },
  SUPPLIER_RETURN_CANCELLED: { severity: 'WARNING', label: 'Retour fournisseur annulé' },
  INVENTORY_COUNT_CHANGED: { severity: 'INFO', label: 'Comptage d’inventaire modifié' },
  PRODUCT_CREATED: { severity: 'INFO', label: 'Produit créé' },
  PRODUCT_UPDATED: { severity: 'INFO', label: 'Produit modifié' },
  PRODUCT_PRICE_CHANGED: { severity: 'INFO', label: 'Prix produit modifié' },
  PRODUCT_DELETED: { severity: 'WARNING', label: 'Produit supprimé (sans historique)' },
  CATALOG_REFERENCE_CHANGED: { severity: 'INFO', label: 'Référentiel du catalogue modifié' },
  CATALOG_IMPORTED: { severity: 'INFO', label: 'Import du catalogue' },
  LOT_BLOCKED: { severity: 'WARNING', label: 'Lot bloqué' },
  LOT_UNBLOCKED: { severity: 'WARNING', label: 'Lot débloqué' },
  LOT_RECALL: { severity: 'WARNING', label: 'Rappel de lot' },
  CLIENT_CREATED: { severity: 'INFO', label: 'Client créé' },
  CLIENT_UPDATED: { severity: 'INFO', label: 'Client modifié' },
  SUPPLIER_CREATED: { severity: 'INFO', label: 'Fournisseur créé' },
  SUPPLIER_UPDATED: { severity: 'INFO', label: 'Fournisseur modifié' },
  CREDIT_LIMIT_OVERRIDE: {
    severity: 'WARNING',
    label: 'Dépassement du plafond de crédit autorisé',
  },
  ADMIN_OVERRIDE: { severity: 'WARNING', label: 'Autorisation par code administrateur' },
  OVERRIDE_FAILED: { severity: 'WARNING', label: 'Échec d’autorisation administrateur' },
  CASH_DISCREPANCY: { severity: 'WARNING', label: 'Écart de caisse' },
  USER_CREATED: { severity: 'CRITICAL', label: 'Utilisateur créé' },
  USER_UPDATED: { severity: 'CRITICAL', label: 'Utilisateur modifié' },
  USER_DISABLED: { severity: 'CRITICAL', label: 'Utilisateur désactivé' },
  USER_ENABLED: { severity: 'CRITICAL', label: 'Utilisateur réactivé' },
  USER_CREDENTIALS_RESET: { severity: 'CRITICAL', label: 'Mot de passe / PIN réinitialisé' },
  PASSWORD_CHANGED: { severity: 'INFO', label: 'Mot de passe modifié' },
  PIN_CHANGED: { severity: 'INFO', label: 'PIN modifié' },
  ROLE_CREATED: { severity: 'CRITICAL', label: 'Rôle créé' },
  ROLE_PERMISSIONS_CHANGED: { severity: 'CRITICAL', label: 'Permissions d’un rôle modifiées' },
  ROLE_DELETED: { severity: 'CRITICAL', label: 'Rôle supprimé' },
  LOGIN_SUCCESS: { severity: 'INFO', label: 'Connexion' },
  LOGIN_FAILED: { severity: 'WARNING', label: 'Échec de connexion' },
  LOGOUT: { severity: 'INFO', label: 'Déconnexion' },
  ACCOUNT_LOCKED: { severity: 'WARNING', label: 'Compte verrouillé' },
  USER_SWITCHED: { severity: 'INFO', label: 'Changement rapide d’utilisateur' },
  SCREEN_UNLOCKED: { severity: 'INFO', label: 'Déverrouillage de l’écran' },
  PIN_FAILED: { severity: 'WARNING', label: 'Échec de saisie du PIN' },
  SESSION_REVOKED: { severity: 'WARNING', label: 'Session révoquée' },
  SETTING_CHANGED: { severity: 'WARNING', label: 'Paramètre modifié' },
  DEVICE_REGISTERED: { severity: 'INFO', label: 'Nouveau poste enregistré' },
  DEVICE_APPROVED: { severity: 'WARNING', label: 'Poste approuvé' },
  DEVICE_REVOKED: { severity: 'WARNING', label: 'Poste révoqué' },
  DEVICE_RENAMED: { severity: 'INFO', label: 'Poste renommé' },
  DATA_EXPORTED: { severity: 'INFO', label: 'Export de données' },
  BACKUP_CREATED: { severity: 'INFO', label: 'Sauvegarde effectuée' },
  BACKUP_FAILED: { severity: 'CRITICAL', label: 'Sauvegarde échouée' },
  BACKUP_RESTORED: { severity: 'CRITICAL', label: 'Sauvegarde restaurée' },
  AUDIT_INTEGRITY_CHECKED: { severity: 'INFO', label: 'Vérification de l’intégrité du journal' },
  AUDIT_INTEGRITY_FAILED: { severity: 'CRITICAL', label: 'Intégrité du journal compromise' },
  STOCK_INCONSISTENCY: { severity: 'CRITICAL', label: 'Incohérence de stock détectée' },
  EMAIL_SENT_MANUALLY: { severity: 'INFO', label: 'Document envoyé par e-mail' },
  EMAIL_CANCELLED: { severity: 'INFO', label: 'Envoi d’e-mail annulé' },
  CLIENT_EMAIL_CONSENT_CHANGED: {
    severity: 'INFO',
    label: 'Consentement e-mail du client modifié',
  },
  NOTIFICATION_SUBSCRIPTIONS_CHANGED: {
    severity: 'INFO',
    label: 'Abonnements aux notifications modifiés',
  },
  EMAIL_TEMPLATE_CHANGED: { severity: 'WARNING', label: 'Modèle d’e-mail modifié' },
} as const satisfies Record<string, { severity: Severity; label: string }>;

export type AuditEventType = keyof typeof events;
export const AUDIT_EVENTS: Record<AuditEventType, { severity: Severity; label: string }> = events;
export const AUDIT_EVENT_TYPES = Object.keys(events) as AuditEventType[];
